export const product1 = [
  {
    title: "Product 1",
    product: [
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
    ],
  },
  {
    title: "Product 2",
    product: [
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
      {
        title: "Product 1",
        description: "Description for product 1",
        price: "198000",
        comment: 20,
        ratting: 4.8,
        img: "https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/xam_nhjat_real_4.jpg",
      },
    ],
  },
];
